### ISSUE TITLE
Whitespaces handling issue

### ISSUE THREAD

**Issue by dcdamien** [zentavr/linet.mikrotik#3]
**Router OS Version**: 6.27

##### SUMMARY
Data passed to zabbix_sender isn't correctly quoted.
For instance `mikrotik.irq[eth phy]` item should be double-quoted bacause of whitespace:

```
- mikrotik.irq[MicroSD] 1536406399 "0"
- mikrotik.irq[ts] 1536406399 "0"
- mikrotik.irq[crypto] 1536406399 "0"
- mikrotik.irq[Fancon] 1536406399 "3127289961"
- mikrotik.irq[eth phy] 1536406399 "5"
- mikrotik.irq[eth] 1536406399 "2694565660"
- mikrotik.irq[eth] 1536406399 "1970755556"
- mikrotik.irq[usb1] 1536406399 "0"
- mikrotik.irq[usb2] 1536406399 "2"
```

##### ISSUE TYPE

 - Bug Report

##### OS / ENVIRONMENT

* OS: `Ubuntu 16.04`
* Python: ` 2.7.12`
* Virtualenv: yes
* pip freeze:
```
chainmap==1.0.2
librouteros==2.1.0
```

##### STEPS TO REPRODUCE

```
/etc/zabbix/.venv/bin/python /etc/zabbix/mikrotik/zabbix.py -H 10.0.21.201 -u zabbix -p password -t
```

##### EXPECTED RESULTS

Quoting should work as noted in `libs/strings.py`:
```
    # + Quoted and non - quoted entries are supported.
    # + Double - quote is the quoting character.
    # + Entries with whitespace must be quoted.
    # + Double - quote and backslash characters inside quoted entry must be escaped with a backslash.
    # + Escaping is not supported in non - quoted entries.
    # + Linefeed escape sequences(\n) are supported in quoted strings.
    # + Linefeed escape sequences are trimmed from the end of an entry.
```

##### ACTUAL RESULTS

Entries with whitespaces aren't double quoted.

**Comment by zentavr** [comment]
@dcdamien - I pushed the code into master. Please check and reopen the issue if the problem still exists.

**Comment by zentavr** [comment]
@dcdamien - it was a small mistake in the code I pushed yesterday, so it was fixed today.

**Comment by dcdamien** [comment]
@zentavr this is fine now but new bug was introduced - #7
