### ISSUE TITLE
Wrong uptime value format

### ISSUE THREAD

**Issue by dcdamien** [zentavr/linet.mikrotik#7]
**Router OS Version**: 6.27

##### SUMMARY
Peer uptime value is rejected by Zabbix Server.

##### ISSUE TYPE

 - Bug Report

##### OS / ENVIRONMENT

* OS: `Ubuntu 16.04`
* Python: ` 2.7.12`
* Virtualenv: yes
* pip freeze:
```
chainmap==1.0.2
librouteros==2.1.0
```

##### STEPS TO REPRODUCE

```
/etc/zabbix/.venv/bin/python /etc/zabbix/mikrotik/zabbix.py -H 10.0.21.201 -u zabbix -p password -t
```

##### EXPECTED RESULTS

Script should convert RouterOS uptime format to seconds.

##### ACTUAL RESULTS

Currently uptime value is passed as original value from RouterOS, for instance `1d5h36m1s` .
```

**Comment by dcdamien** [comment]
@zentavr this was introduced in c03b0d25dd02b05515314015f0c399701c5fea5f.
`time_convert` function is no longer used.

**Comment by zentavr** [comment]
@dcdamien - I submitted bf68f6a, please check.

**Comment by dcdamien** [comment]
@zentavr this is fine now, working as expected 👌
