### ISSUE TITLE
Script fails on disabled peers

### ISSUE THREAD

**Issue by dcdamien** [zentavr/linet.mikrotik#8]
**Router OS Version**: 6.27

##### SUMMARY
Script crashes on disabled peers.

##### ISSUE TYPE

 - Bug Report

##### OS / ENVIRONMENT

* OS: `Ubuntu 16.04`
* Python: ` 2.7.12`
* Virtualenv: yes
* pip freeze:
```
chainmap==1.0.2
librouteros==2.1.0
```

##### STEPS TO REPRODUCE

```
/etc/zabbix/.venv/bin/python /etc/zabbix/mikrotik/zabbix.py -H 10.0.21.201 -u zabbix -p password -t
```

##### EXPECTED RESULTS

Script should handle disabled peers which lacks fileds such as `state` and `uptime`.

##### ACTUAL RESULTS

Currently script throws an error because `status` and `uptime` keys are missing.

**Comment by zentavr** [comment]
Hello @dcdamien,

Thank you for the report.
I will check this and back to you later.
